[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "xts"
version = "2.0.0"
dependencies = [
    "rich>=13.7.1",
    "pyinstaller>=6.12.0",
    "requests>=2.32.3",
    "rich-argparse>=1.7.2",
    "importlib_resources>=7.1.0",
    "yaml_runner @ git+https://github.com/rdkcentral/yaml_runner.git@2.2.0",
    "argparse_completion @ git+https://github.com/rdkcentral/argparse_completion.git@1.0.0"
]
[tool.setuptools.packages.find]
include = ["xts_core*"]
where = ["src"]
namespaces = false

# --- Include non-Python files ---
[tool.setuptools.package-data]
# If your data folder is *inside* xts_core, use this:
xts_core = ["data/**/*"]

# --- Include data outside packages ---
[tool.setuptools]
include-package-data = true

# This ensures data/ is included in sdist/wheel
[tool.setuptools.data-files]
# Installs data into a shared location in site-packages
"xts_core_data" = ["data/**/*"]

[project.scripts]
xts-install = "xts_core.install:main"
xts = "xts_core.xts:main"
